### ISSUE TITLE
Map is not big enough for tablets

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#102]
Map is not big enough when using the app on a tablet.
Steps to reproduce:
1. Open the app on a tablet (Open it on Google Chrome and change the screen size to "iPad" in developer mode.
2. See that the map is cut halfway through in the bottom of the screen in both portrait and landscape mode

![Screen Shot 2020-02-21 at 11.45.56 PM.png](https://images.zenhubusercontent.com/5e1e1c208231a25c23ef7c9f/83cf030c-a84e-46f1-9f7d-123804f98bcc)

**Comment by alecadub** [comment]
@tedgag this ticket is invalid, the height of the map is dynamically set once you open the map! If you refresh your page, the app will check the height of your device and set it! It's normal if you switch from a phone/tablet in the dev tools that it won't work!

![image](https://user-images.githubusercontent.com/39540423/75179739-bc603d00-5708-11ea-9f62-1846c264e6c7.png)
