### ISSUE TITLE
As a user, I need a button to switch between Indoor and Outdoor Views

### ISSUE THREAD

**Issue by RjDrury** [claudiiafg/MapConU#103]
Currently in the app, it was requires a code change to swap from indoor to outdoor and vice versa. We need to implement a button to take us inside a building and to take us out of a building.

https://www.figma.com/file/GWTIDHydeRLSbnt2GM9qF5/MapConU?node-id=39%3A12

**Comment by GwenLegate** [comment]
I was planning to actually implement this as part the building information popups since the button is on that popup in the mockup.  It's good to have it as an explicit issue though.

**Comment by GwenLegate** [comment]
implement indoor, outdoor pages and routing

**Comment by tedgag** [comment]
The "direction" button on the outdoor pop-up menu should take us to the indoor map of the building.
Clicking the back button on the phone should take us back to the outdoor view.
Should implement this with Angular routing.

https://www.figma.com/file/GWTIDHydeRLSbnt2GM9qF5/MapConU?node-id=39%3A12

<img width="148" alt="Screen Shot 2020-02-26 at 9 37 54 PM" src="https://user-images.githubusercontent.com/36055308/75407142-41517f00-58e0-11ea-8621-d60efcdbfdf6.png">

**Comment by GwenLegate** [comment]
It's currently implemented as "Map" takes you indoors.  "Direction" has been changed to "Go" because of spacing issues and gives you a path from your location to the building

**Comment by GwenLegate** [comment]
Current Implementation only takes you to a default indoor view.  We need to decide how routing will be done between floors
-a page for each floor? 
-one page for indoors and reload the necessary components on that page?

**Comment by claudiiafg** [comment]
done in #94 and #129
