### ISSUE TITLE
css changes in last merge to master caused dropdown menus to appear in the wrong place

### ISSUE THREAD

**Issue by GwenLegate** [claudiiafg/MapConU#104]
I didn't notice before I merged yesterday but one of the css changes make the drop down menus show up in the wrong place!  We need to take a look at the merged code, find the change responsible and correct it

**Comment by claudiiafg** [comment]
I'm currently working on the points of interest popup, so I can fix that...

**Comment by GwenLegate** [comment]
Thanks!!  I think it's an issue we've had before

**Comment by claudiiafg** [comment]
Yeah i think so too, will be working on it today

**Comment by alecadub** [comment]
Currently:

![image](https://user-images.githubusercontent.com/39540423/75176086-781d6e80-5701-11ea-9553-d3dc8a7c3866.png)

Should be:

![image](https://user-images.githubusercontent.com/39540423/75176119-8ec3c580-5701-11ea-9de1-1c18736a8e4e.png)
