### ISSUE TITLE
As a developer, I need to get points coordinates for the floor maps (Classes, corridor intersections, classes corners)

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#112]
Get X Y coordinates for the classes, corridor intersections and corners of the classes (to highlight them)

**Comment by achung98** [comment]
Get the (x,y) points of the image for corridors, classes, POIs, etc. Each point will act as a node. With these nodes create some edges.

Get the (x,y) points of the class edges. This will be used when specifying the start an end locations rooms.

**Comment by achung98** [comment]
Store this points into some sort of a database. SQLite or Firebase as options.

**Comment by achung98** [comment]
Not needed anymore since it's included in #118
