### ISSUE TITLE
As a developper, I need to store and retrieve indoor points as objects from the database

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#114]
- Name (room number)
- Type (Classes, bathroom)
- X, Y coordinates
- Reachable points (Collection of other point objects)
- Vertices coordinates of the room: Counterclockwise starting from bottom-left (Collection of points)

**Comment by claudiiafg** [comment]
everything is done directly in the svg file, when the page is open we retrieve the information from that the html, there's no need for database.

**Comment by tedgag** [comment]
Agreed, will close this issue
