### ISSUE TITLE
As a developer, I need to draw two points and the path between them based on a point object

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#115]
A point object has:

- Name (room number)
- Type (Classes, bathroom)
- X, Y coordinates
- Reachable points (Collection of other point objects)
- Vertices coordinates of the room: Counterclockwise starting from bottom-left (Collection of points)

We need to find out how to draw a line between two point object in TypeScript.

<img width="114" alt="Screen Shot 2020-02-26 at 9 50 12 PM" src="https://user-images.githubusercontent.com/36055308/75407836-f9335c00-58e1-11ea-980d-fc842ce50e7f.png">

**Comment by achung98** [comment]
Not needed anymore since it's included in #118

**Comment by claudiiafg** [comment]
done in #129
