### ISSUE TITLE
As a user, I am able to know the distance between two classes

### ISSUE THREAD

**Issue by alecadub** [claudiiafg/MapConU#12]
The user should be able to know the distance between the two destination they chose to get directions.
<img width="159" alt="Screen Shot 2020-03-11 at 12 42 19 AM" src="https://user-images.githubusercontent.com/36055308/76383104-2bf14180-6331-11ea-98ed-ff422b2bd203.png">

**Comment by claudiiafg** [comment]
All lines in a path have a certain length -> calculate total length of path
