### ISSUE TITLE
poi popups not dismissing

### ISSUE THREAD

**Issue by GwenLegate** [claudiiafg/MapConU#126]
I ran into a bug with the poi popups.  Sometimes they don't dismiss properly but I'm not sure what triggers it because most of the time the feature works as expected.  I had this happen when I was testing the branch as well but couldn't re create it so I thought it was an isolated glitch.

![image](https://user-images.githubusercontent.com/46829100/75579725-740c8c00-5a34-11ea-80ae-9fbafb3565e8.png)

Here all options are un-selected but I cant make the markers dismiss!

**Comment by GwenLegate** [comment]
I just managed to do it again when I went indoors than back to outdoors I wasn't able to un-select an option I had previously highlighted.  The next time I tried to do this by switching from indoors to outdoors it worked properly though.  

It's not consistent but it seems to show up when we do something else without un-selecting the icons and try to un-select them after

**Comment by claudiiafg** [comment]
I was able to reproduce this before but now I can't seem to do it again.. If someone can please tell me the steps

**Comment by GwenLegate** [comment]
We can probably close this issue.  I wasn't able to consistently re-create it when I first found it and I haven't seen it since Claudia refactored the code when changing the markers so it was probably fixed un-intentionally.

**Comment by claudiiafg** [comment]
Agree, this bug hasn't been observed in 2 sprints, I believe it was fixed with some other issue
