### ISSUE TITLE
The user should be able to click a button so that the app centers on my current position.

### ISSUE THREAD

**Issue by claudiiafg** [claudiiafg/MapConU#148]
The user should be able to click a button so that the app centers on their current position.

**Comment by tedgag** [comment]
Added the button to the mockups, only thing left to do is implement it.
<img width="366" alt="Screen Shot 2020-03-23 at 4 55 26 PM" src="https://user-images.githubusercontent.com/36055308/77362323-1adc0380-6d27-11ea-967b-5e89f3bf3c2a.png">
