### ISSUE TITLE
As a user, I need to be able to search for Concordia building when searching for outdoor locations or directions

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#159]
The user should be able to search for Concordia school buildings using the outdoor search-bar, and clicking on the building should move the map to the building's location.

**Comment by alecadub** [comment]
Change the type to ['establishment', 'geocode'] instead of ['address'] in search popover.ts, just tested it and it works

![image](https://user-images.githubusercontent.com/39540423/76780847-142c1a00-6784-11ea-94f9-149a4cf8e732.png)

**Comment by tedgag** [comment]
Has already been fixed by implementing another feature in https://github.com/claudiiafg/MapConU/pull/184
