### ISSUE TITLE
As a user, I want to see a path to get me from my current classroom to my next classroom

### ISSUE THREAD

**Issue by alecadub** [claudiiafg/MapConU#2]

**Comment by achung98** [comment]
Mock ups:
![mockup1](https://user-images.githubusercontent.com/20468491/75123167-03035800-5673-11ea-9ef3-0ce2563c8fd4.png)

![mockup2](https://user-images.githubusercontent.com/20468491/75123184-28906180-5673-11ea-8980-a89432914179.png)

Comments:
1. agm-overlays for inserting the floor plan
2. indoor atlas sdk for indoor wayfinding, possibility of indoor positioning
3. indoor atlas positioning api to fetch floor plan data (or we could hard code them, or use a db?)
4. agm-directions to show the directions on the map //to check

Resources:
1. https://www.npmjs.com/package/agm-overlays
2. https://docs.indooratlas.com/cordova/latest/
3. https://docs.indooratlas.com/positioning-api#/
4. https://www.npmjs.com/package/agm-direction

**Comment by achung98** [comment]
Fetch the graph of the floor from the database. Compute A* shortest path algorithm to compute the directions to the class.

Resources:
https://briangrinstead.com/blog/astar-search-algorithm-in-javascript/

**Comment by claudiiafg** [comment]
done in #129
