### ISSUE TITLE
As a developer, I need to implement the Concordia shuttle bus API

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#209]

**Comment by claudiiafg** [comment]
Documentation: https://github.com/opendataConcordiaU/documentation

**Comment by claudiiafg** [comment]
Map tracking bus location: http://shuttle.concordia.ca/concordiabusmap/

**Comment by RjDrury** [comment]
Confirmed the https://github.com/opendataConcordiaU/documentation does not provide updates bus info.
