### ISSUE TITLE
As a developer, I need to fix the bugs in the SonarQube report

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#256]

**Comment by GwenLegate** [comment]
![image](https://user-images.githubusercontent.com/46829100/79626065-52a65300-80fb-11ea-8558-34b76142cfeb.png)

Current SonarQube report on master 04/17/2020

**Comment by GwenLegate** [comment]
A lot of the issues flagged by SonarQube are actually in the HTML files generated by out TypeDoc.  I'm going to fix any larger issues that I can in our code then do another report but move the TypeDoc files out of the MapConU folder this time.

**Comment by GwenLegate** [comment]
New SonarQube run with some of the recommended changes made and the TypeDoc HTML code removed.

![image](https://user-images.githubusercontent.com/46829100/79674466-7b891f80-81b1-11ea-80f2-805e6de7c0b5.png)
