### ISSUE TITLE
Minor bug with selecting a day from the calendar

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#269]
When selecting a day with an event, the event drop down shows up and remain when selecting a day previous from today's date.

For example, today is April 1, and clicking on March 29 after clicking on April 1 does not remove the dropdown:
<img width="311" alt="Screen Shot 2020-04-01 at 2 58 32 PM" src="https://user-images.githubusercontent.com/36055308/78176148-0b953e00-742a-11ea-8a99-e5ebf4f33165.png">

**Comment by achung98** [comment]
This happens because they are not from the same month. I don't think this is an issue.
Nevertheless, I spotted a small bug similar to this. When clicking on a day with events then moving to another month, the drop down remains even if that day does not include any events. Will work on that.
