### ISSUE TITLE
Indoor directions 9th floor bugs

### ISSUE THREAD

**Issue by GwenLegate** [claudiiafg/MapConU#282]
When creating the indoor poi's I found a couple of bugs in the 9th floor code.

shows poi markers for male and female washrooms:
![image](https://user-images.githubusercontent.com/46829100/78816489-cd56cc00-799f-11ea-87bc-d06c6b3a7e1e.png)

tapping the screen in the area of the leftmost bathroom marker gives the user the option to get directions to this location:
![image](https://user-images.githubusercontent.com/46829100/78816570-e95a6d80-799f-11ea-9f6c-bb6c93f2c278.png)

tapping on "This Floor" should give the user directions to the washroom that was clicked from the default point of entry to the 9th floor (escalator):

![image](https://user-images.githubusercontent.com/46829100/78816668-0bec8680-79a0-11ea-940c-150ef75b2b7b.png)

tapping "go" gives the user directions to the other bathroom poi marker on the rhs:
![image](https://user-images.githubusercontent.com/46829100/78816781-2f173600-79a0-11ea-8de2-b121f054e214.png)

The locations of the classrooms I tried and the elevator, escalator.

*I did have an issue where I clicked on the SW stairs location and got directions to the SE stairs instead but it didn't happen again, maybe the click directions issues are related to the directions popups not closing properly and not the 9th floor code itself?

**Comment by achung98** [comment]
I'm not able to replicate the bugs, can you check again ?

**Comment by GwenLegate** [comment]
> I'm not able to replicate the bugs, can you check again ?

I did it again and it worked fine this time.  I noticed that I had a similar issue with the stairs where sometimes clicking on sw stairs took you to se stairs etc... but it wasn't consistent so I'm thinking it's actually a bug related to the indoor directions popups not closing properly and not the actual 9th floor code.  When I was setting the poi's I was repeatedly checking the directions to several different combinations of locations and that's when I noticed the bugs.  Today checking the bathroom directions was the only thing I did when I opened the App.

**Comment by achung98** [comment]
> > I'm not able to replicate the bugs, can you check again ?
> 
> I did it again and it worked fine this time. I noticed that I had a similar issue with the stairs where sometimes clicking on sw stairs took you to se stairs etc... but it wasn't consistent so I'm thinking it's actually a bug related to the indoor directions popups not closing properly and not the actual 9th floor code. When I was setting the poi's I was repeatedly checking the directions to several different combinations of locations and that's when I noticed the bugs. Today checking the bathroom directions was the only thing I did when I opened the App.

I'm gonna close the issue then
