### ISSUE TITLE
Spacing of indoor locations for start and end points isn't wide enough for the longer french translation

### ISSUE THREAD

**Issue by GwenLegate** [claudiiafg/MapConU#287]
![image.png](https://images.zenhubusercontent.com/5e1d1e84e924e36eb5b750dc/b0f561f2-a9e7-46ec-9238-6304f51fe115)

1. Go to the indoor view (app language needs to be set to french)
2. Tap on the compass icon or a location on the floor plan to trigger the indoor direction popup
3. Tap on either the start point or end point input locations to trigger another popup with a list of indoor locations to select from and scroll through to find locations that don't fit.

This may be the case for english as well on some phones with smaller screens but it hasn't been an issue for me.

**Comment by tedgag** [comment]
I think the way it is is fine as it is, it's better than resizing the drop down to accommodate the text size. Will close this issue
