### ISSUE TITLE
As a developper, I need to create the splash screen

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#32]
Create a splash screen to replace the default Ionic splash screen

**Comment by alecadub** [comment]
The user should be able to see the splash screen at launch. The team needs to:

- Add the logo to the assets
- Show splash screen until fetching of the data for google maps is done.

**Comment by claudiiafg** [comment]
Since this is low priority and just an enhancement, we could probably move it to sprint 3 @tedgag
