### ISSUE TITLE
As a user, I want to find the nearest outdoor point of interests from my current location

### ISSUE THREAD

**Issue by alecadub** [claudiiafg/MapConU#4]
Mock ups to follow:
![3](https://user-images.githubusercontent.com/20468491/75485125-23cff400-5978-11ea-87ed-2b814e5134d5.png)

- POI should display POI based on the current selected campus.
- POI should be marked on the map.

**Comment by achung98** [comment]
Mock ups to follow:
![3](https://user-images.githubusercontent.com/20468491/75484776-680ec480-5977-11ea-85e4-fa20c239f173.png)

- POI should display POI based on the current selected campus.
- POI should be marked on the map.
