### ISSUE TITLE
As a user, I want to be able to find indoor Point of Interests (water fountain, toilet, etc.)

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#49]
The user should be able to select indoors point of interests from a list and have them shown on his map. The user should also be able to get directions to those points of interest as well.

<img width="161" alt="Screen Shot 2020-03-11 at 12 36 29 AM" src="https://user-images.githubusercontent.com/36055308/76382836-5abae800-6330-11ea-9785-a955419d20a9.png">

**Comment by tedgag** [comment]
Put the point of interests that we know about and that we can get from the pictures

**Comment by GwenLegate** [comment]
New commit has different icons for each poi and icons by each poi for better inclusivity for people with disabilities.

.lang-icon {
  width: 40px;
  height: 40px;
}

I double checked the locations of the washrooms for H9 but they match the circles so I'm not sure what bug in H9 makes it wonky. I'm going to look into it more tonight and try to get rid of the upside down marker that just lives on the H9 map for some reason now.

**Comment by GwenLegate** [comment]
feature merged 04/09/2020
