### ISSUE TITLE
As a developer, I need to manually label the rest of the floor maps

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#51]
Add room number to every classes in the available floor maps and add it to the Google Drive (see: https://drive.google.com/drive/folders/1XH8IWBqQ6DBygnL40flVt1_n1y5lo1uJ)

**Comment by claudiiafg** [comment]
Since we started by mb1 (easier to compute path because less options) this issue should be pushed for next sprint. @tedgag
