### ISSUE TITLE
Component diagram 

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#55]
# Component Diagram for the MapConU application

## Components are as follow: 
* Google-API 
* Google Calendar
*

# Domain Model ???

## Subdomains
* User
* Map (Navigation)

Description WIP

**Comment by miche-cho** [comment]
Component Diagram uploaded onto Google Drive under [Software Architecture Folder](https://drive.google.com/drive/folders/1HcWvpdN8Oh81RoNDEUnImcoo7iTLLECM?usp=sharing)

**Comment by achung98** [comment]
- APIs should not be components, just interfaces given
- Location and map should be connected by an interface (From location to map, or maybe both ways?)
- Navigation and map should be connected by an interface (From navigation to map or both ways?)
- Event to location and navigation, one way
