### ISSUE TITLE
As a user, I want to sign using my Google Account for Google Calendar

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#58]
The user should be able to sign in to their Google account in the setting page of the app, so they can access the Google calendar functionalities. 

<img width="286" alt="Screen Shot 2020-03-11 at 12 40 42 AM" src="https://user-images.githubusercontent.com/36055308/76383028-f2203b00-6330-11ea-83b9-272ad9d1b77f.png">

**Comment by achung98** [comment]
- Implement google oauth

Resources: https://ionicthemes.com/tutorials/about/ionic-google-login
