### ISSUE TITLE
As a developer, I need to implement UI changes proposed by client during the sprint 1 meeting

### ISSUE THREAD

**Issue by GwenLegate** [claudiiafg/MapConU#81]
- Highlighting concordia buildings → want that too (marker is not enough)
- Need button to click into indoor map (supposed to be in the mouse over/ pop up menu for building 
- Maybe changing transportation methods to icons instead of text
- UI colour scheme → something less intense (differentiate source and destination)
- Add time and and show route before pressing go
-Add button to swap destination and current location

**Comment by GwenLegate** [comment]
building highlighting completed, ready to merge.

**Comment by tedgag** [comment]
Mockups have been updated to reflect the changes, see:

https://www.figma.com/file/GWTIDHydeRLSbnt2GM9qF5/MapConU?node-id=39%3A12

**Comment by claudiiafg** [comment]
Highlighting concordia buildings done in #80

**Comment by claudiiafg** [comment]
Need button to click into indoor map done in #94

**Comment by claudiiafg** [comment]
Add time and show route before pressing go done in #5

**Comment by claudiiafg** [comment]
Changing transportation methods to icons instead of text - done in #5

**Comment by claudiiafg** [comment]
UI colour scheme - done in #129
