### ISSUE TITLE
As a developper, I need to add unit tests to the Google API components

### ISSUE THREAD

**Issue by GwenLegate** [claudiiafg/MapConU#82]
Create unit tests with Jasmine and Karma related to the following user stories:

- [x] As a user I want to view building information
- [x] As a user I want to see my current location on the map
- [x] As a user, I am able to toggle between campuses view using a toggle button on the screen

**Comment by claudiiafg** [comment]
Since we're removing firebase and just using local storage, this issue is probably no longer necessary

**Comment by KevinHTrinh** [comment]
Updated the description to only include the Google API component user stories.
