### ISSUE TITLE
As a developer, I need to create a quality measurements report with SonarQube

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#87]
Metrics to measure using SonarQube: 

- Cyclomatic Complexity
- Duplicated blocks, files and lines 
- Maintainability rating
- Reliability rating
- Security rating 
- Source lines of code (SLOC)

**Comment by KevinHTrinh** [comment]
![image](https://user-images.githubusercontent.com/36750342/75622175-994fe600-5b6b-11ea-88a3-3905b9675de2.png)
![image](https://user-images.githubusercontent.com/36750342/75622181-b1c00080-5b6b-11ea-855a-b10918507967.png)
