### ISSUE TITLE
As a developer, I need to generate code coverage report for sprint 2 with Karma

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#88]
Generate a code coverage report at the end of the sprint using Karma and add it to the deliverable.

![image](https://user-images.githubusercontent.com/36055308/75408009-7eb70c00-58e2-11ea-9a57-d9c71ef85f5c.png)

**Comment by KevinHTrinh** [comment]
![image](https://user-images.githubusercontent.com/36750342/75622244-4b87ad80-5b6c-11ea-9cd7-aab2c67a8c7f.png)
