### ISSUE TITLE
As a developer, I need to update software diagrams (component + domain) for sprint 2

### ISSUE THREAD

**Issue by tedgag** [claudiiafg/MapConU#91]
Domain diagram and component diagram should reflect changes made during sprint 2. 
Diagrams are used as reference material to review software architecture and components that are employed in the software

- [x] Domain diagram should be updated with association between locations entity and routeguidance entity
- [x] Update component diagram
 - [x] Review if diagrams reflect software architecture

**Comment by miche-cho** [comment]
![DomainModel2](https://user-images.githubusercontent.com/30091849/75281488-68735800-57dd-11ea-987f-a5e724a0b6f8.png)

**Comment by tedgag** [comment]
Teacher comments:
Software Architecture [2.5/4]
RouteGuidance needs two Locations (start, destination) in order to provide directions.
Overall, the domain model is making good use of abstractions.
The use of Firebase is not justified. Why do you need to save preferences in the cloud?
There is no discussion about alternative libraries that could be used (advantages disadvantages compared to the selected ones)

**Comment by miche-cho** [comment]
> 
> 
> Teacher comments:
> Software Architecture [2.5/4]
> RouteGuidance needs two Locations (start, destination) in order to provide directions.
> Overall, the domain model is making good use of abstractions.
> The use of Firebase is not justified. Why do you need to save preferences in the cloud?
> There is no discussion about alternative libraries that could be used (advantages disadvantages compared to the selected ones).
> 
> Can you verify that the issues have been resolved?

RouteGuidance has been solved with the association as suggested by the professor
